[project]
name = "ja-txt-analytics-for-game"
version = "0.1.0"
description = "Game store review text analytics for Japanese text"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.0",
    "janome>=0.5.0",
    "pyyaml>=6.0.0"
]

[tool.setuptools]
packages = ["src"]
