# モバイルゲームレビュー分析カテゴリ定義
game_review_categories:
  
  # ゲームメカニクス関連カテゴリ
  game_mechanics:
    name: "ゲームメカニクス"
    subcategories:
      core_gameplay:
        name: "コアゲームプレイ"
        keywords: ["バトル", "戦闘", "操作", "コントロール", "バランス", "難易度", "システム", "ゲームプレイ", "プレイ感", "操作性", "アクション", "コマンド", "フィールド", "ダンジョン", "攻撃", "ダメージ", "防御", "回避", "ヒット", "コンボ", "ゲーム性", "バトルシステム", "戦闘システム", "操作感", "操作方法"]
      progression:
        name: "プログレッション"
        keywords: ["成長", "レベル", "レベルアップ", "スキル", "強化", "育成", "レア", "ステータス", "能力", "装備", "武器", "防具", "アイテム", "属性", "進化", "限界突破", "覚醒", "昇級", "解放", "素材", "上昇", "成長要素", "レベル上限", "能力値", "スキルツリー"]
      matching:
        name: "マッチング"
        keywords: ["マッチング", "PvP", "対戦", "協力", "マルチ", "ギルド", "クラン", "フレンド", "オンライン", "対人", "協力プレイ", "野良", "リアルタイム", "ソロ", "ランク", "ランキング", "報酬", "パーティ", "ギルドバトル", "クランマッチ", "フレンド機能"]
      replayability:
        name: "リプレイ性"
        keywords: ["やり込み", "周回", "繰り返し", "飽き", "コンテンツ", "ボリューム", "単調", "変化", "多様性", "コツコツ", "毎日", "日課", "やりこみ", "要素", "充実", "豊富", "不足", "コンテンツ量", "やり込み要素", "コンテンツ不足"]
  
  # コンテンツ関連カテゴリ
  content:
    name: "コンテンツ"
    subcategories:
      main_content:
        name: "メインコンテンツ"
        keywords: ["メイン", "クエスト", "ストーリー", "ミッション", "シナリオ", "ステージ", "章", "冒険", "クリア", "攻略", "難易度", "メインストーリー", "物語", "展開", "メインクエスト", "ストーリーモード"]
      sub_content:
        name: "サブコンテンツ"
        keywords: ["サブ", "収集", "探索", "サイド", "やりこみ", "隠し", "発見", "支線", "オプション", "図鑑", "コレクション", "サブクエスト", "サブストーリー", "サイドストーリー", "収集要素", "探索要素"]
      event:
        name: "期間限定イベント"
        keywords: ["イベント", "期間限定", "キャンペーン", "シーズン", "フェス", "コラボ", "ログイン", "ボーナス", "ミッション", "報酬", "配布", "限定", "交換", "収集", "ランキング", "期間限定イベント", "イベントクエスト"]
      update:
        name: "アップデート"
        keywords: ["アップデート", "バージョン", "更新", "改善", "修正", "パッチ", "追加", "実装", "新機能", "バグ", "調整", "変更", "刷新", "拡張", "新規", "アップデート内容", "バージョンアップ", "パッチノート"]
  
  # キャラクター・世界観関連カテゴリ
  characters_and_world:
    name: "キャラクター・世界観"
    subcategories:
      character_design:
        name: "キャラクターデザイン"
        keywords: ["キャラ", "キャラクター", "デザイン", "見た目", "衣装", "外見", "容姿", "ビジュアル", "イラスト", "魅力", "個性", "可愛い", "かわいい", "カッコいい", "かっこいい", "キャラクターデザイン", "キャラデザ"]
      story:
        name: "ストーリー"
        keywords: ["ストーリー", "物語", "シナリオ", "展開", "ナラティブ", "描写", "セリフ", "台詞", "演出", "感動", "ドラマ", "伏線", "結末", "オチ", "ストーリー展開", "ストーリーテリング"]
      world_setting:
        name: "世界観"
        keywords: ["世界観", "設定", "背景", "舞台", "ユニバース", "雰囲気", "歴史", "文化", "神話", "ファンタジー", "SF", "未来", "過去", "異世界", "現代", "世界設定", "世界背景"]
      voice_sound:
        name: "ボイス・サウンド"
        keywords: ["ボイス", "声優", "音声", "BGM", "サウンド", "音楽", "効果音", "SE", "歌", "テーマ曲", "オープニング", "エンディング", "ボイスアクト", "声優陣", "BGM品質"]
  
  # 視覚・聴覚体験カテゴリ
  visual_and_audio:
    name: "視覚・聴覚体験"
    subcategories:
      graphics:
        name: "グラフィック"
        keywords: ["グラフィック", "グラフィックス", "画質", "美麗", "綺麗", "きれい", "美しい", "迫力", "解像度", "テクスチャ", "描画", "映像", "美術", "アート", "グラフィッククオリティ", "描画品質"]
      animation:
        name: "アニメーション"
        keywords: ["アニメーション", "動き", "モーション", "エフェクト", "演出", "カットシーン", "ムービー", "滑らか", "なめらか", "ぬるぬる", "カクカク", "キャラモーション", "モーション品質"]
      ui_ux:
        name: "UI/UX"
        keywords: ["UI", "インターフェース", "画面", "メニュー", "操作性", "使いやすさ", "見やすさ", "分かりやすさ", "わかりやすさ", "レイアウト", "ユーザーインターフェース", "UIデザイン"]
      loading:
        name: "ロード時間"
        keywords: ["ロード", "読み込み", "待ち時間", "処理", "遅延", "重い", "軽い", "動作", "サクサク", "カクカク", "もっさり", "ラグ", "遅い", "速い", "早い", "起動", "ロード時間", "読み込み速度"]
  
  # ビジネスモデル関連カテゴリ 
  business_model:
    name: "ビジネスモデル"
    subcategories:
      payment:
        name: "課金システム"
        keywords: ["課金", "値段", "価格", "コスパ", "有料", "無料", "購入", "買う", "買った", "セール", "割引", "還元", "石", "ジェム", "コイン", "通貨", "チケット", "課金要素", "無課金", "微課金"]
      gacha:
        name: "ガチャ"
        keywords: ["ガチャ", "確率", "排出", "天井", "ピックアップ", "重複", "被り", "かぶり", "欲しい", "出ない", "爆死", "運", "引く", "回す", "SSR", "SR", "R", "レア", "当たり", "ガチャシステム"]
      subscription:
        name: "バトルパス/サブスク"
        keywords: ["サブスク", "月額", "バトルパス", "シーズンパス", "プレミアム", "特典", "パス", "定期", "会員", "有料", "無料", "サブスクリプション", "バトルパスシステム"]
      ads:
        name: "広告"
        keywords: ["広告", "CM", "アド", "宣伝", "リワード", "報酬", "動画", "視聴", "スキップ", "表示", "頻度", "頻繁", "邪魔", "うざい", "広告視聴", "リワード広告"]
  
  # コミュニティ・サポート関連カテゴリ
  community_and_support:
    name: "コミュニティ・サポート"
    subcategories:
      customer_support:
        name: "カスタマーサポート"
        keywords: ["サポート", "問い合わせ", "対応", "お問い合わせ", "連絡", "返信", "運営", "スタッフ", "カスタマー", "反応", "回答", "解決", "助け", "カスタマーサポート", "サポート対応"]
      communication:
        name: "コミュニケーション"
        keywords: ["運営", "開発者", "情報", "発信", "公式", "Twitter", "SNS", "告知", "お知らせ", "透明性", "誠意", "コミュニケーション", "説明", "運営からのお知らせ", "公式Twitter"]
      community:
        name: "コミュニティ"
        keywords: ["コミュニティ", "交流", "フレンド", "ギルド", "クラン", "チャット", "掲示板", "協力", "ソーシャル", "マルチ", "友達", "知人", "コミュニティ機能", "フレンド機能"]
      accessibility:
        name: "アクセシビリティ"
        keywords: ["初心者", "チュートリアル", "説明", "ガイド", "ヘルプ", "ビギナー", "難しい", "簡単", "分かりやすい", "わかりやすい", "手引き", "初心者向け", "チュートリアルモード"]
  
  # ユーザー体験段階別カテゴリ
  user_experience_stages:
    name: "ユーザー体験段階"
    subcategories:
      early_experience:
        name: "初期体験"
        keywords: ["最初", "始め", "チュートリアル", "導入", "初心者", "スタート", "はじめ", "序盤", "第一印象", "オープニング", "登録", "初期体験", "導入部", "チュートリアルパート"]
      mid_experience:
        name: "中期体験"
        keywords: ["中盤", "継続", "モチベーション", "やる気", "飽き", "日課", "ルーティン", "コツコツ", "毎日", "ログイン", "デイリー", "ウィークリー", "進行", "成長", "中期体験", "継続モチベーション"]
      late_experience:
        name: "後期体験"
        keywords: ["後半", "終盤", "エンドコンテンツ", "やり込み", "極限", "極み", "高難度", "上級者", "熟練", "マスター", "コンプリート", "完成", "エンドコンテンツ", "後期体験"]
      comeback_experience:
        name: "復帰体験"
        keywords: ["復帰", "カムバック", "戻って", "久しぶり", "離れてた", "再開", "ブランク", "休止", "引退", "辞めてた", "やめてた", "復帰ボーナス", "カムバックキャンペーン"]
  
  # 技術的側面カテゴリ
  technical_aspects:
    name: "技術的側面"
    subcategories:
      stability:
        name: "安定性"
        keywords: ["クラッシュ", "落ちる", "強制終了", "バグ", "不具合", "エラー", "フリーズ", "固まる", "停止", "安定", "不安定", "安定性", "アプリクラッシュ", "強制終了", "アプリ落ち"]
      device_compatibility:
        name: "デバイス互換性"
        keywords: ["端末", "機種", "スマホ", "タブレット", "Android", "iPhone", "iOS", "動作", "対応", "互換性", "非対応", "スペック", "CPU", "メモリ", "端末対応", "機種対応"]
      network:
        name: "通信"
        keywords: ["通信", "回線", "Wi-Fi", "オフライン", "オンライン", "切断", "接続", "同期", "ラグ", "遅延", "通信量", "データ量", "パケット", "通信エラー", "ネットワークエラー"]
      update_frequency:
        name: "アップデート頻度"
        keywords: ["頻度", "間隔", "定期", "頻繁", "更新", "アップデート", "メンテナンス", "バージョンアップ", "改善", "修正", "追加", "アップデート頻度", "アップデート間隔"]

# 感情分析用の主要表現（簡略版）
sentiment_words:
  positive: ["良い", "いい", "素晴らしい", "すばらしい", "楽しい", "たのしい", "面白い", "おもしろい", "最高", "さいこう", "好き", "すき", "気に入る", "きにいる", "満足", "まんぞく", "神", "かみ", "すごい", "凄い", "すげー", "やばい", "優れる", "優秀", "便利", "べんり", "簡単", "かんたん", "わかりやすい", "分かりやすい", "綺麗", "きれい", "美しい", "うつくしい", "格好いい", "かっこいい", "萌える", "萌え", "可愛い", "かわいい", "感動", "かんどう", "快適", "かいてき", "軽い", "かるい", "親切", "しんせつ", "丁寧", "ていねい"]
  
  negative: ["悪い", "わるい", "ひどい", "酷い", "つまらない", "詰まらない", "最悪", "さいあく", "嫌い", "きらい", "不満", "ふまん", "苦痛", "くつう", "ストレス", "すとれす", "難しい", "むずかしい", "めんどくさい", "面倒", "わからない", "分からない", "理解できない", "意味不明", "いみふめい", "バグ", "ばぐ", "不具合", "ふぐあい", "エラー", "えらー", "重い", "おもい", "遅い", "おそい", "落ちる", "おちる", "課金", "かきん", "搾取", "さくしゅ", "高い", "たかい", "しぶい", "渋い", "出ない", "でない", "爆死", "ばくし", "改善", "かいぜん", "改悪", "かいあく", "詐欺", "さぎ", "騙された", "だまされた", "飽きる", "あきる", "単調", "たんちょう", "微妙", "びみょう"]

# 否定表現パターン（簡略版）
negation_patterns: ["ない", "ません", "なかった", "ませんでした", "ぬ", "ず", "ないで", "なくて", "ないが", "ないけど", "ないけれど", "ないです", "はずだった"]

# カテゴリ別重み付け
category_weights:
  game_mechanics: 1.2
  content: 1.1
  characters_and_world: 0.9
  visual_and_audio: 0.8
  business_model: 1.3
  community_and_support: 0.7
  user_experience_stages: 1.0
  technical_aspects: 1.1